### ISSUE TITLE
How to Change to button mode

### ISSUE THREAD

**Issue by FlibbleTiggon** [Krxwallo/CheatMode#1]
Im probably just a dunce but how exactly do I change it from auto open to button mode?

**Comment by Krxwallo** [comment]
Sorry for having to wait so long. Should work now... (a3d1082fe9e1fb26695a36fd291ce5f054642012)

**Comment by Krxwallo** [comment]
Change the config file at %appdata%/.minecraft/config/cheat_mode-common.toml
