### ISSUE TITLE
actually puts you into creative mode

### ISSUE THREAD

**Issue by Karma262** [Krxwallo/CheatMode#12]
I have no no clue when or how this happens but its happened on two worlds so far. I open the creative inventory with the button thing and next thing I know when I exit I'm actually in creative mode, and from what i've tried you cant go back with out commands.

**Comment by Krxwallo** [comment]
Is that when you exit normally or when it gets force-exited by something?

**Comment by Karma262** [comment]
> Is that when you exit normally or when it gets force-exited by something?

didn't even know things could force close your inv so that could be it. since it temporarily puts you into creative it probably just gets frozen to creative if your forced out
