### ISSUE TITLE
【Forge/1.19】Unknown Crash

### ISSUE THREAD

**Issue by AmyRose1288** [Krxwallo/CheatMode#13]
[latest.log](https://github.com/Krxwallo/CheatMode/files/9239046/latest.log)
[crash-2022-08-02_12.33.07-fml.txt](https://github.com/Krxwallo/CheatMode/files/9239047/crash-2022-08-02_12.33.07-fml.txt)

java.lang.reflect.InvocationTargetException: null

Edit:Forge 41.1.0 Minecraft 1.19 No Optifine Installed

**Comment by Krxwallo** [comment]
fixed in https://github.com/Krxwallo/CheatMode/commit/57bcde31ea2f9b608e4e7baf4fb7f2805117d16d
