### ISSUE TITLE
Invisible "Open Creative Inventory" toggle.

### ISSUE THREAD

**Issue by kezben01** [Krxwallo/CheatMode#19]
I'm in an online server where I am opped/have gamemode permissions, but when I go to click the grass block to open the creative inventory, the block is missing, though the "Open Creative Inventory" text box still appears. When I click where the text box appears nothing happens.

**Comment by Krxwallo** [comment]
mc version?
mod version?
forge or fabric?

**Comment by kezben01** [comment]
mc version: 1.18.2
mod version: v1.2.5 1.18.X
Forge

**Comment by kezben01** [comment]
Also, it works perfectly fine in my singleplayer world, it is just the server where the issue is occurring.

**Comment by Krxwallo** [comment]
Please re-open if still present in newest (1.21) version :)
