### ISSUE TITLE
Can't Open The Configuration

### ISSUE THREAD

**Issue by TheGuyNobodyKnow** [Krxwallo/CheatMode#21]
When I was creating the world with cheat mode. I entered the world. i open inventory, it working good,but can't change to survival inventory. Then i try press Shift Right to open the configuration. I can't, i change so many version to check, but it same.

**Comment by Krxwallo** [comment]
When you are using version 1.20 the configuration is in the chat screen. There is no config that opens with Right Shift.

**Comment by Krxwallo** [comment]
On the 1.16.5 versions, you have to change the config options manually in the config file located at MINECRAFT_DIRECTORY/config/cheat_mode-common.toml
