### ISSUE TITLE
Compatibility with 1.20.1

### ISSUE THREAD

**Issue by moggiex** [Krxwallo/CheatMode#22]
Howdy, 

Can we have compatibility with the latest version please :)

Thanks!

M

**Comment by Krxwallo** [comment]
Have you tried if the version for 1.20 also works for 1.20.1?

**Comment by moggiex** [comment]
> Have you tried if the version for 1.20 also works for 1.20.1?

I did look, honest! Where is it hiding :P

M

**Comment by moggiex** [comment]
Ooo found it! Under alpha files on Curseforge.

Could I suggest a few links from the readme.md file to the diff versions?

And of course, thank you.

M

**Comment by moggiex** [comment]
[itzg-minecraft-server-forge.zip](https://github.com/Krxwallo/CheatMode/files/12117620/itzg-minecraft-server-forge.zip)

See attached, fails on load.

M

**Comment by Krxwallo** [comment]
Cheat Mode is only supported on the client side.
