### ISSUE TITLE
Pressing up in the text menu makes it impossible to type

### ISSUE THREAD

**Issue by echovoidheart** [Krxwallo/CheatMode#24]
Since the menu for the config of this mod is in the text menu, if I ever end up pressing the up arrow in that menu my cursor jumps up to the buttons of the config and I'm not able to interact with the text box at all after that. I have to completely close the menu in order to type at all again. This means I can't use commands because trying to retrieve any previous command I've sent just disables the menu entirely.

**Comment by Krxwallo** [comment]
Fixed in https://github.com/Krxwallo/CheatMode/commit/99d5bedcfd23a3c2c0fe1bd96203093e67536d2a
