### ISSUE TITLE
My questions

### ISSUE THREAD

**Issue by ghost** [Krxwallo/CheatMode#27]
1) is this a mod?
2) am I allowed to convert the code if even possible? 
3) how to put onto minecraft?
4) am I allowed to try and modify the code so it can work on mcpe or bedrock?

If answer yes to questions 2 and 4 then if I succeed I will ask if I can post and if u say yes I will also credit you. But if you say no then I will just keep the stuff to myself.  

Or if you want if I succeed in converting the code into a zip file of c++ code I can send it through discord. And you can out it here. I don't really care if people credit me or not btw so ye. 

Srry for writing so much tho.

**Comment by Krxwallo** [comment]
1. Yes this is a mod.
2, 3, 4. Yes, of course you can convert the mod, however I dont know bedrock stuff so i cannot be of assistance.
You dont have to credit me but a link to the java version would be nice.

**Comment by ghost** [comment]
Alright I'll do that if I can successfully convert it.

**Comment by ghost** [comment]
Ima try these (https://www.quora.com/What-is-the-best-tool-for-converting-Java-source-code-to-cpp?top_ans=1477743633153993)

Oh by the way does this work on realms that are not mine?

And is it a texture pack or addon?

**Comment by Krxwallo** [comment]
Like I said, I have never worked with bedrock mods before. However, I am pretty sure that using a converter will not work and you will have to basically rewrite the mod/addon from scratch. For that you need knowledge on how to develop minecraft mods/addons for the Bedrock Edition.

**Comment by ghost** [comment]
> Like I said, I have never worked with bedrock mods before. However, I am pretty sure that using a converter will not work and you will have to basically rewrite the mod/addon from scratch. For that you need knowledge on how to develop minecraft mods/addons for the Bedrock Edition.

I managed to convert it so now I will test it and see if it works but I have to figure out how to test it first

**Comment by ghost** [comment]
Mission failed. Code don't work with mcpe even with conversions and if made into a mcpack or mcaddon or even apk it won't work. So it would have to be made from scratch. And I don't know how to code very well so I can't do it. So yeah.
