### ISSUE TITLE
Cant go  back to survival curseforge 1.19.2

### ISSUE THREAD

**Issue by tirruxi** [Krxwallo/CheatMode#30]
I used the mod and sadly my game crashed and it was stuck on creative. Any tips how i could get it back to survival. Been trying to find survival fix for 1.19 but i couldnt find.

**Comment by Krxwallo** [comment]
I am sorry, but the survival fix is currently only available for 1.21. The easiest way for you would be to upgrade to 1.21...

**Comment by tirruxi** [comment]
How can i upgrade it to 1.21

**Comment by Krxwallo** [comment]
You have to upgrade your game and install neoforge for 1.21 from [neoforged.net](https://neoforged.net)

**Comment by tirruxi** [comment]
Okay. How do i switch the 1.19 world to 1.21 when ive dowwnloaded neoforged

**Comment by Krxwallo** [comment]
You should see the old world when you launch 1.21 and it will ask you if you want to convert it.

**Comment by tirruxi** [comment]
Yeah but isnt curseforge and neoforge  a different thing meaning i cant launch my curseforge world with neoforge. I opened mc with neoforge only and it didnt ask nothing

**Comment by Krxwallo** [comment]
Ohhhh sorry I misunderstood. When using the curseforge launcher there should be a way to launch neoforge 1.21 from in there. I don't know how the curseforge launcher works but you should be able to find both the 1.19 worlds folder and the 1.21 World folder and copy your world to 1.21...

**Comment by Krxwallo** [comment]
You can also copy your world from curseforge to neoforge, it doesn't matter how you do it.

**Comment by tirruxi** [comment]
Ok. So does that mean i have to play that world with neoforge instead of curseforge?

**Comment by Krxwallo** [comment]
There are also a lot of tutorials on this topic online :)

**Comment by Krxwallo** [comment]
Oh another thing: I forgot that I only fixed the survival bug for fabric so you will have to wait until I fix it for forge :/

**Comment by tirruxi** [comment]
oh okay. Will you hit me up when youre ready with that.

**Comment by tirruxi** [comment]
Hey. i found a mod i can change gamemode and it worked. No problem anymore

**Comment by Krxwallo** [comment]
Perfect!

**Comment by Krxwallo** [comment]
Bug is also fixed for neoforge 3.0.2-beta
