### ISSUE TITLE
Spamming or clicking opening Inventory turns your character into creative mode

### ISSUE THREAD

**Issue by Satobi64** [Krxwallo/CheatMode#31]
Spamming or clicking opening **"Inventory Key"** turns your character into **creative mode** forever and the only way to go back from survival is to edit the player save file.

**Comment by kberix** [comment]
Can you please state your mc version and mod version? Are you talking about the forge or the fabric version?

**Comment by Krxwallo** [comment]
Can you please state your mc version and mod version? Are you talking about the forge or the fabric version?

**Comment by Zodeian** [comment]
Ive had a similar problem im on 1.19.2 for version and using forge ive been stuck in creative. Ive resorted to save editing to fix it

**Comment by Krxwallo** [comment]
Please try out the v3.0.2-beta version for 1.21 and lmk if you still have the same issue.

**Comment by Krxwallo** [comment]
Please re-open the issue if it still persists for you with the version mentioned above.
