### ISSUE TITLE
Config Auto resetting

### ISSUE THREAD

**Issue by 9oeu** [Krxwallo/CheatMode#5]
When i change the config aswell as the default to (false) everytime i restart my game it resets  and I am unable to switch back to survival mode, the grass block doesn't appear in the menu and changing the config ingame/in the menu doesn't work/change anything.
![Capture](https://user-images.githubusercontent.com/56745566/108625294-2264ca80-7418-11eb-8176-4f42c39180f2.PNG)

**Comment by Krxwallo** [comment]
u dont have to restart ur game. and changing the comments doesnt change the default value. what if you dont restart, but try it out in the game right after u saved the config ?

**Comment by 9oeu** [comment]
I don't know how but it fixed itself, maybe I needed to restart my game again, but anyway I've got a new problem so im gonna close this one and make a new one.

**Comment by Krxwallo** [comment]
Lol ok
