### ISSUE TITLE
cheat mode seems to duplicate items in regular survival mode

### ISSUE THREAD

**Issue by xapkkpax** [Krxwallo/CheatMode#6]
hi, i changed the config so that i can open creative mode in survival mode by pressing e and then selecting the grass block to open creative from there. but it seems to always duplicate anything i touch or eat on survival. I crafted ONE pickaxe, and then i suddenly had three. when i threw away all but one, it was fine. then when i ate one apple, it created three. i am confused if this is a glitch or not, but i do not like it one bit. help???

**Comment by Krxwallo** [comment]
🤣 I'll have 2 work on that

**Comment by Krxwallo** [comment]
So its only when you set it 2 not instantly open?

**Comment by xapkkpax** [comment]
hmmmm... i have not yet tried it with default settings. the reason i got the mod was because i have minecolonies and i dont want to cheat my world. only thing i will being using creative is with the building because of the materials. i really do love the mod though! i dont have it in my mods list now, but when i start building, ill readd it, with all the kinks and stuff too:). i dont mind the accidental duplication, i just didnt know if that was me or the settings i chose. thanks for replying!

**Comment by lucasmarques13** [comment]
multiplayer version is complete?

**Comment by sa6rija** [comment]
i have just installed the mod and i want to make the mod to open it not by pressing E, but by pressing other button. The problem is that i cant enable it cuz im new on minecraft and i dont now much about folders,mods,etc...
I NEED HELP !

**Comment by Krxwallo** [comment]
@sa6rija 
1. That has nothing to do with this issue
2. The config folder is mostly located at `%appdata%\.minecraft\config`
